export const ANALYSIS_START = 'ANALYSIS_START';
export const ANALYSIS_ERROR = 'ANALYSIS_ERROR';
export const SET_TICKER_ERROR = 'SET_TICKER_ERROR';
export const SET_DATA_AND_ANALYSIS = "SET_DATA_AND_ANALYSIS";